In [2]:
import torch

checkpoint = torch.load("split/saved_models/custom/rosenbrock_0.pth.tar", weights_only=False)

In [3]:
checkpoint

{'cfg': [(1, 4)],
 'split_index': '0',
 'state_dict': OrderedDict([('layers.0.linear.weight',
               tensor([[0.1947],
                       [0.1519],
                       [0.1250]], device='cuda:0')),
              ('layers.0.linear.bias',
               tensor([ 0.2322, -0.2594,  0.5207], device='cuda:0')),
              ('linear.weight',
               tensor([[-0.0589,  0.0055, -0.0908]], device='cuda:0')),
              ('linear.bias', tensor([0.0625], device='cuda:0'))]),
 'args': Namespace(dataset='rosenbrock', batch_size=64, test_batch_size=64, epochs=10, lr=0.001, momentum=0.9, load='split/saved_models/custom/finetune/rosenbrock_0.pth.tar', no_cuda=False, seed=1, log_interval=100, split_index='0', energy=False, params=False, save='split/saved_models/custom', grow=0.3, exp_name='custom', start_from_retrain=False, rd=0, cuda=True)}

In [10]:
print(checkpoint['state_dict']['linear.weight'])

tensor([[-0.0589,  0.0055, -0.0908]], device='cuda:0')


In [12]:
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(2, 2),
    nn.Sigmoid(),
    nn.Linear(2, 1)
)

In [15]:
for module, param in model.named_parameters():
    print(module, param.shape)

0.weight torch.Size([2, 2])
0.bias torch.Size([2])
2.weight torch.Size([1, 2])
2.bias torch.Size([1])
