In [3]:
import torch

checkpoint_path = "split/saved_models/custom/rosenbrock_0.pth.tar"

checkpoint = torch.load(checkpoint_path, weights_only=False)

In [4]:
checkpoint

{'cfg': [(1, 4), (3, 1)],
 'split_index': '0',
 'state_dict': OrderedDict([('layers.0.linear.weight',
               tensor([[1.8182],
                       [1.8217],
                       [1.5790]], device='cuda:0')),
              ('layers.0.linear.bias',
               tensor([ 1.8444, -1.8537,  2.7200], device='cuda:0')),
              ('layers.1.linear.weight',
               tensor([[ 2.4868,  2.4395, -2.8727]], device='cuda:0')),
              ('layers.1.linear.bias', tensor([2.5648], device='cuda:0'))]),
 'args': Namespace(dataset='rosenbrock', batch_size=64, test_batch_size=64, epochs=10, lr=0.001, momentum=0.9, load='split/saved_models/custom/finetune/rosenbrock_0.pth.tar', no_cuda=False, seed=1, log_interval=100, split_index='0', energy=False, params=False, save='split/saved_models/custom', grow=0.3, exp_name='custom', start_from_retrain=False, rd=0, cuda=True)}